<?php

class Frontend_Css extends Frontend {

	public function frontend () {
		return $this->view('frontend');
	}

	public function backend () {
		return $this->view('backend');
	}
	
	private function view ($type) {
		global $__modules_path;

		$rep = Repository::getInstance();
		$req = Request::getInstance();

		if ($this->get(1) == false) {
			throw new Exception_HTTP(404);
		}

		$method = 'load_' . $type;
		if (($mod = $rep->$method($req->get(1))) == false) {
			throw new Exception_HTTP(404);			
		}

		$res = Response::getInstance();
		$res->set_content_type('text/css');

		// List module and its ancestors + abstract superclass 'module'
		$modules = array();
		$modules[] = 'module';
		foreach (array_merge($rep->get_dependencies($this->get(1), $type), array($mod)) as $module) {
			$modules[] = $module->get_module_name();
		}

		$css = "/* Aggregated Stylesheet\n   Auto-Generated by TCMS\n*/\n";
		foreach ($modules as $name) {
			$dir = $__modules_path . '/' . $name . '/' . $type . '/css/';
			if (is_dir($dir)) {
				$d = opendir($dir);
				while (($file = readdir($d)) !== false) {
					if (substr($file, -4) == '.css') {
						$css .= "\n/* " . $dir . $file . " */\n";
						$css .= file_get_contents($dir . $file);
					}
				}
			}

		}
		return $css;
	}

}

?>