<?php

class Frontend_Css extends Frontend {

	private $css = '';

	public function frontend () {
		$this->css = $this->generate_css('frontend');
	}

	public function backend () {
		$this->css = $this->generate_css('backend');
	}

	public function render ($view = 'dummy') {
		return $this->css;
	}

	private function generate_css ($type) {
		global $__modules_path;

		$rep = Repository::getInstance();
		$req = Request::getInstance();

		if ($this->get(1) == false) {
			return STATUS_NOT_FOUND;
		}

		$method = 'load_' . $type;
		if (($module = $rep->$method($req->get(1))) == false) {
			return STATUS_NOT_FOUND;
		}

		$res = Response::getInstance();
		$res->set_content_type('text/css');

		// List module and its ancestors + abstract superclass 'module'
		$modules = array();
		$modules[] = 'module';
		foreach (array_merge($module->get_dependencies($type), array($module)) as $dependency) {
			$modules[] = $dependency->get_module_name();
		}

		$css = "/* Aggregated Stylesheet\n   Auto-Generated by TCMS\n*/\n";
		foreach ($modules as $name) {
			$dir = $__modules_path . '/' . $name . '/' . $type . '/css/';
			if (is_dir($dir)) {
				$d = opendir($dir);
				while (($file = readdir($d)) !== false) {
					if (substr($file, -4) == '.css') {
						$css .= "\n/* " . $dir . $file . " */\n";
						$css .= file_get_contents($dir . $file);
					}
				}
			}

		}
		return $css;
	}

}

?>